<template><div><h2 id="堆参数调整-以1-8-hotspot为例" tabindex="-1"><a class="header-anchor" href="#堆参数调整-以1-8-hotspot为例"><span>堆参数调整 -- 以1.8 + HotSpot为例</span></a></h2>
<h3 id="jdk-7" tabindex="-1"><a class="header-anchor" href="#jdk-7"><span>JDK 7</span></a></h3>
<img :src="$withBase('/jvm/cs1.png')" alt="dock">
--------------------------------------------------------
<h3 id="jdk-8" tabindex="-1"><a class="header-anchor" href="#jdk-8"><span>JDK 8</span></a></h3>
<img :src="$withBase('/jvm/cs.png')" alt="dock">
<ul>
<li>jdk8以后永久代被移除，被一个称作元空间的代替。区别在于永久代使用JVM的堆内存，<strong>元空间使用本机的物理内存。</strong>
<ul>
<li>因此默认情况下，元空间大小仅受本地内存限制，类的元数据放入本地内存，字符串池和类的常量放入java的<code v-pre>堆heap</code>中,这样可以加载多少类的元数据不再由MaxPermSize控制。</li>
</ul>
</li>
</ul>
<h3 id="堆内存调优参数" tabindex="-1"><a class="header-anchor" href="#堆内存调优参数"><span>堆内存调优参数</span></a></h3>
<p>参数 | 说明 |</p>
<ul>
<li>| :-: | :-: | :-: | -:
-Xms | 设置初始分配大小，默认为物理内存的1/64 |
-Xmx | 设置分配最大内存，默认为物理内存的1/4 |
-XX:+PrintGCDetails | 输出详细的GC处理日志</li>
</ul>
<div class="hint-container tip">
<p class="hint-container-title">Tips</p>
<p>-Xss 是调栈空间</p>
</div>
<ul>
<li>查看参数方法</li>
</ul>
<div class="language-java line-numbers-mode" data-highlighter="prismjs" data-ext="java"><pre v-pre><code><span class="line"> <span class="token keyword">public</span> <span class="token keyword">static</span> <span class="token keyword">void</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token class-name">String</span><span class="token punctuation">[</span><span class="token punctuation">]</span> args<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">//java虚拟机试图使用最大内存量</span></span>
<span class="line">    <span class="token keyword">long</span> max <span class="token operator">=</span> <span class="token class-name">Runtime</span><span class="token punctuation">.</span><span class="token function">getRuntime</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">maxMemory</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token comment">//java虚拟机中的内存总量</span></span>
<span class="line">    <span class="token keyword">long</span> total <span class="token operator">=</span> <span class="token class-name">Runtime</span><span class="token punctuation">.</span><span class="token function">getRuntime</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">totalMemory</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token comment">//这个是-Xmx参数设置的内存大小</span></span>
<span class="line">    <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"-Xmx -- MAX_MEMORY= "</span><span class="token operator">+</span><span class="token punctuation">(</span>max<span class="token operator">/</span><span class="token punctuation">(</span><span class="token keyword">double</span><span class="token punctuation">)</span><span class="token number">1024</span><span class="token operator">/</span><span class="token number">1024</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">"MB"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token comment">//这个是-Xms参数设置的内存</span></span>
<span class="line">    <span class="token class-name">System</span><span class="token punctuation">.</span>out<span class="token punctuation">.</span><span class="token function">println</span><span class="token punctuation">(</span><span class="token string">"-Xm -- TOTAL_MEMORY= "</span><span class="token operator">+</span><span class="token punctuation">(</span>total<span class="token operator">/</span><span class="token punctuation">(</span><span class="token keyword">double</span><span class="token punctuation">)</span><span class="token number">1024</span><span class="token operator">/</span><span class="token number">1024</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">"MB"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="调整参数" tabindex="-1"><a class="header-anchor" href="#调整参数"><span>调整参数</span></a></h3>
<div class="hint-container tip">
<p class="hint-container-title">Tips</p>
<p>-Xmx -Xmx 把两者设置为一致,是为了避免频繁扩容和GC释放堆内存造成的系统开销/压力</p>
</div>
<h3 id="gc收集日志信息-xx-printgcdetails" tabindex="-1"><a class="header-anchor" href="#gc收集日志信息-xx-printgcdetails"><span>GC收集日志信息 -XX:+PrintGCDetails</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code><span class="line"><span class="token punctuation">[</span>GC <span class="token punctuation">(</span>Allocation Failure<span class="token punctuation">)</span> <span class="token punctuation">[</span>PSYoungGen: 1708K-<span class="token operator">></span>504K<span class="token punctuation">(</span>2560K<span class="token punctuation">)</span><span class="token punctuation">]</span> 1708K-<span class="token operator">></span>688K<span class="token punctuation">(</span>9728K<span class="token punctuation">)</span>, <span class="token number">0.0033197</span> secs<span class="token punctuation">]</span> <span class="token punctuation">[</span>Times: <span class="token assign-left variable">user</span><span class="token operator">=</span><span class="token number">0.00</span> <span class="token assign-left variable">sys</span><span class="token operator">=</span><span class="token number">0.00</span>, <span class="token assign-left variable">real</span><span class="token operator">=</span><span class="token number">0.00</span> secs<span class="token punctuation">]</span> </span>
<span class="line"><span class="token punctuation">[</span>GC <span class="token punctuation">(</span>Allocation Failure<span class="token punctuation">)</span> <span class="token punctuation">[</span>PSYoungGen: 504K-<span class="token operator">></span>496K<span class="token punctuation">(</span>2560K<span class="token punctuation">)</span><span class="token punctuation">]</span> 688K-<span class="token operator">></span>768K<span class="token punctuation">(</span>9728K<span class="token punctuation">)</span>, <span class="token number">0.0004713</span> secs<span class="token punctuation">]</span> <span class="token punctuation">[</span>Times: <span class="token assign-left variable">user</span><span class="token operator">=</span><span class="token number">0.00</span> <span class="token assign-left variable">sys</span><span class="token operator">=</span><span class="token number">0.00</span>, <span class="token assign-left variable">real</span><span class="token operator">=</span><span class="token number">0.00</span> secs<span class="token punctuation">]</span> </span>
<span class="line"><span class="token punctuation">[</span>Full GC <span class="token punctuation">(</span>Allocation Failure<span class="token punctuation">)</span> <span class="token punctuation">[</span>PSYoungGen: 496K-<span class="token operator">></span>0K<span class="token punctuation">(</span>2560K<span class="token punctuation">)</span><span class="token punctuation">]</span> <span class="token punctuation">[</span>ParOldGen: 272K-<span class="token operator">></span>619K<span class="token punctuation">(</span>7168K<span class="token punctuation">)</span><span class="token punctuation">]</span> 768K-<span class="token operator">></span>619K<span class="token punctuation">(</span>9728K<span class="token punctuation">)</span>, <span class="token punctuation">[</span>Metaspace: 3290K-<span class="token operator">></span>3290K<span class="token punctuation">(</span>1056768K<span class="token punctuation">)</span><span class="token punctuation">]</span>, <span class="token number">0.0040743</span> secs<span class="token punctuation">]</span> <span class="token punctuation">[</span>Times: <span class="token assign-left variable">user</span><span class="token operator">=</span><span class="token number">0.00</span> <span class="token assign-left variable">sys</span><span class="token operator">=</span><span class="token number">0.00</span>, <span class="token assign-left variable">real</span><span class="token operator">=</span><span class="token number">0.00</span> secs<span class="token punctuation">]</span> </span>
<span class="line"><span class="token punctuation">[</span>GC <span class="token punctuation">(</span>Allocation Failure<span class="token punctuation">)</span> <span class="token punctuation">[</span>PSYoungGen: 0K-<span class="token operator">></span>0K<span class="token punctuation">(</span>2560K<span class="token punctuation">)</span><span class="token punctuation">]</span> 619K-<span class="token operator">></span>619K<span class="token punctuation">(</span>9728K<span class="token punctuation">)</span>, <span class="token number">0.0001987</span> secs<span class="token punctuation">]</span> <span class="token punctuation">[</span>Times: <span class="token assign-left variable">user</span><span class="token operator">=</span><span class="token number">0.00</span> <span class="token assign-left variable">sys</span><span class="token operator">=</span><span class="token number">0.00</span>, <span class="token assign-left variable">real</span><span class="token operator">=</span><span class="token number">0.00</span> secs<span class="token punctuation">]</span> </span>
<span class="line"><span class="token punctuation">[</span>Full GC <span class="token punctuation">(</span>Allocation Failure<span class="token punctuation">)</span> <span class="token punctuation">[</span>PSYoungGen: 0K-<span class="token operator">></span>0K<span class="token punctuation">(</span>2560K<span class="token punctuation">)</span><span class="token punctuation">]</span> <span class="token punctuation">[</span>ParOldGen: 619K-<span class="token operator">></span>601K<span class="token punctuation">(</span>7168K<span class="token punctuation">)</span><span class="token punctuation">]</span> 619K-<span class="token operator">></span>601K<span class="token punctuation">(</span>9728K<span class="token punctuation">)</span>, <span class="token punctuation">[</span>Metaspace: 3290K-<span class="token operator">></span>3290K<span class="token punctuation">(</span>1056768K<span class="token punctuation">)</span><span class="token punctuation">]</span>, <span class="token number">0.0039539</span> secs<span class="token punctuation">]</span> <span class="token punctuation">[</span>Times: <span class="token assign-left variable">user</span><span class="token operator">=</span><span class="token number">0.00</span> <span class="token assign-left variable">sys</span><span class="token operator">=</span><span class="token number">0.00</span>, <span class="token assign-left variable">real</span><span class="token operator">=</span><span class="token number">0.00</span> secs<span class="token punctuation">]</span> </span>
<span class="line">Heap</span>
<span class="line"> PSYoungGen      total 2560K, used 56K <span class="token punctuation">[</span>0x00000000ffd00000, 0x0000000100000000, 0x0000000100000000<span class="token punctuation">)</span></span>
<span class="line">  eden space 2048K, <span class="token number">2</span>% used <span class="token punctuation">[</span>0x00000000ffd00000,0x00000000ffd0e348,0x00000000fff00000<span class="token punctuation">)</span></span>
<span class="line">  from space 512K, <span class="token number">0</span>% used <span class="token punctuation">[</span>0x00000000fff00000,0x00000000fff00000,0x00000000fff80000<span class="token punctuation">)</span></span>
<span class="line">  to   space 512K, <span class="token number">0</span>% used <span class="token punctuation">[</span>0x00000000fff80000,0x00000000fff80000,0x0000000100000000<span class="token punctuation">)</span></span>
<span class="line"> ParOldGen       total 7168K, used 601K <span class="token punctuation">[</span>0x00000000ff600000, 0x00000000ffd00000, 0x00000000ffd00000<span class="token punctuation">)</span></span>
<span class="line">  object space 7168K, <span class="token number">8</span>% used <span class="token punctuation">[</span>0x00000000ff600000,0x00000000ff696620,0x00000000ffd00000<span class="token punctuation">)</span></span>
<span class="line"> Metaspace       used 3322K, capacity 4496K, committed 4864K, reserved 1056768K</span>
<span class="line">  class space    used 362K, capacity 388K, committed 512K, reserved 1048576K</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><img :src="$withBase('/jvm/gcDetails.png')" alt="dock">
</div></template>


